# Generated by Django 2.0.3 on 2018-03-21 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('artist_type', models.CharField(default='musician', max_length=150)),
                ('genre', models.CharField(default='', max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('soundcloud_id', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swiped_on', models.DateTimeField(auto_now_add=True)),
                ('liked', models.BooleanField(default=False)),
                ('matched', models.BooleanField(default=False)),
                ('artist_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='artist_match.ArtistProfile')),
                ('artist_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_you', to='artist_match.ArtistProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='artist_match.Like')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='artist_match.ArtistProfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='artist_match.ArtistProfile')),
            ],
        ),
    ]
