# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

beta_settings:
    cloud_sql_instances: vybe-198723:us-east1:vybe-instance

runtime_config:
  python_version: 3
# [END runtime]
