# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 03:19
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name')),
                ('city_class', models.CharField(choices=[('primary', 'Primary City'), ('nearby', 'Nearby City'), ('suburb', 'Suburb')], default='primary', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=3)),
                ('continent', models.CharField(choices=[('na', 'North America'), ('sa', 'South America'), ('eu', 'Europe'), ('as', 'Asia'), ('af', 'Africa'), ('au', 'Austrailia')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='cities.City')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default='United States', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cities.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='parent_city',
            field=models.ManyToManyField(blank=True, null=True, related_name='_city_parent_city_+', to='cities.City'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cities.State'),
        ),
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together=set([('slug', 'city')]),
        ),
    ]
