# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placelist',
            name='places',
            field=models.ManyToManyField(related_name='included_in', to='lists.Place'),
        ),
    ]
